BUSINESS_STRATEGY = "BUSINESS_STRATEGY"
PRODUCT_ANALYTICS = "PRODUCT_ANALYTICS"
SQL_INVESTIGATION = "SQL_INVESTIGATION"
VISUALIZATION = "VISUALIZATION"

ALL_INTENTS = [BUSINESS_STRATEGY, PRODUCT_ANALYTICS, SQL_INVESTIGATION, VISUALIZATION]